name: Build tiny-httpd binaries

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            output: tiny-httpd-linux
          - os: ubuntu-latest
            goos: darwin
            goarch: amd64
            output: tiny-httpd-mac-intel
          - os: ubuntu-latest
            goos: darwin
            goarch: arm64
            output: tiny-httpd-mac-arm
          - os: ubuntu-latest
            goos: windows
            goarch: amd64
            output: tiny-httpd-windows.exe

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build ${{ matrix.output }}
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${{ matrix.output }} ./cmd/tiny-httpd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: dist/${{ matrix.output }}
